version: "2"
services:
 database:
   image: mysql:latest
   environment:
     - MYSQL_DATABASE=mortadhadatabse
     - MYSQL_USER=mortadha
     - MYSQL_PASSWORD=mortadha
     - MYSQL_ROOT_PASSWORD=rootpassword
   ports:
     - 3366:3306
 web:
   image: mortadha123/timesheetdevops:31
   depends_on:
     - database
   ports:
     - 8088:8088
   environment:
     - SPRING_DATASOURCE_URL=jdbc:mysql://database:3306/mortadhadatabse?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true
     - DATABASE_NAME=mortadhadatabse
     - DATABASE_PORT=3306
     - DATABASE_USER=mortadha
     - SPRING_DATASOURCE_USERNAME=mortadha
     - SPRING_DATASOURCE_PASSWORD=mortadha
 grafana:
    image: grafana/grafana:latest
    ports:
    - 3000:3000